version: '3.8'

services:
  stock-data-visualization:
    container_name: stock-data-visualization
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app:cached
    environment:
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped
